spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:

        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**

        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**

        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointment/**


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost


server:
  port: 8989