spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:

        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost


server:
  port: 8989